"""Списки пар по стратегиям (из ТЗ бэктеста)."""

BRK_LONG_PAIRS = [
    "DASHUSDT", "THEUSDT", "INJUSDT", "DOTUSDT", "COTIUSDT", "CAKEUSDT",
    "ETCUSDT", "ICPUSDT", "NILUSDT", "PENGUUSDT", "PYTHUSDT", "RAYUSDT",
    "RENDERUSDT", "SAGAUSDT", "TIAUSDT", "TRUMPUSDT", "XLMUSDT", "ZENUSDT",
    "ZROUSDT", "AVAXUSDT",
]

BRK_SHORT_PAIRS = [
    "ENAUSDT", "SOLUSDT", "XPLUSDT", "ETHFIUSDT", "VIRTUALUSDT", "ZECUSDT",
    "BANKUSDT", "DEXEUSDT", "ENSOUSDT", "ICPUSDT", "RAYUSDT", "TRUMPUSDT",
]

MR_LONG_PAIRS = [
    "BICOUSDT", "CRVUSDT", "PENDLEUSDT", "SAGAUSDT", "SOLUSDT", "STRKUSDT",
    "SUIUSDT", "VIRTUALUSDT", "XPLUSDT", "ADAUSDT", "ARBUSDT", "DEXEUSDT",
    "ENAUSDT", "ENSOUSDT", "INJUSDT", "JUPUSDT", "MORPHOUSDT", "PENGUUSDT",
    "RAYUSDT", "UNIUSDT", "WLDUSDT", "ZECUSDT",
]

MR_SHORT_PAIRS = [
    "SYNUSDT", "ACEUSDT", "BABYUSDT", "BTCUSDT", "ENSOUSDT", "TAOUSDT",
    "XLMUSDT", "XPLUSDT", "ARUSDT", "CAKEUSDT", "CRVUSDT", "FETUSDT",
    "INJUSDT", "RAYUSDT", "SEIUSDT", "TRUMPUSDT", "WLDUSDT",
]

# Все уникальные для предзагрузки
ALL_PAIRS = sorted(
    set(BRK_LONG_PAIRS + BRK_SHORT_PAIRS + MR_LONG_PAIRS + MR_SHORT_PAIRS)
)

PAIRS_BY_STRATEGY = {
    "BRK_LONG": BRK_LONG_PAIRS,
    "BRK_SHORT": BRK_SHORT_PAIRS,
    "MR_LONG": MR_LONG_PAIRS,
    "MR_SHORT": MR_SHORT_PAIRS,
}


def pairs_for_phase(phase: str) -> list[str]:
    if phase == "UPTREND":
        return list(BRK_LONG_PAIRS)
    if phase == "DOWNTREND":
        return list(BRK_SHORT_PAIRS)
    # RANGE
    return sorted(set(MR_LONG_PAIRS + MR_SHORT_PAIRS))
